//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RTI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified format could not be fully recognized as an angular measurement..
        /// </summary>
        internal static string Angle_InvalidFormat {
            get {
                return ResourceManager.GetString("Angle_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interval must be a value greater than zero, between 0 and 60..
        /// </summary>
        internal static string Angle_InvalidInterval {
            get {
                return ResourceManager.GetString("Angle_InvalidInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format for Angle.ToString() method..
        /// </summary>
        internal static string Angle_InvalidToStringFormat {
            get {
                return ResourceManager.GetString("Angle_InvalidToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the right-most number of a sexagesimal measurement can be a fractional value..
        /// </summary>
        internal static string Angle_OnlyRightmostIsDecimal {
            get {
                return ResourceManager.GetString("Angle_OnlyRightmostIsDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Common_Empty {
            get {
                return ResourceManager.GetString("Common_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinity.
        /// </summary>
        internal static string Common_Infinity {
            get {
                return ResourceManager.GetString("Common_Infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified format could not be fully recognized as a distance measurement..
        /// </summary>
        internal static string Distance_InvalidFormat {
            get {
                return ResourceManager.GetString("Distance_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The numeric portion of the distance measurement could not be recognized..
        /// </summary>
        internal static string Distance_InvalidNumericPortion {
            get {
                return ResourceManager.GetString("Distance_InvalidNumericPortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit portion of the distance measurement could not be recognized..
        /// </summary>
        internal static string Distance_InvalidUnitPortion {
            get {
                return ResourceManager.GetString("Distance_InvalidUnitPortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified format could not be fully recognized as a latitude..
        /// </summary>
        internal static string Latitude_InvalidFormat {
            get {
                return ResourceManager.GetString("Latitude_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hemisphere specified for the ToHemisphere method cannot be &apos;None&apos;.  A value of &apos;North&apos; or &apos;South&apos; is The hemisphere specified for the ToHemisphere method cannot be &apos;None&apos;.  A value of &apos;North&apos; or &apos;South&apos; is required..
        /// </summary>
        internal static string Latitude_InvalidHemisphere {
            get {
                return ResourceManager.GetString("Latitude_InvalidHemisphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the right-most number can be a floating-point value..
        /// </summary>
        internal static string Latitude_OnlyRightmostIsDecimal {
            get {
                return ResourceManager.GetString("Latitude_OnlyRightmostIsDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified format could not be fully recognized as a longitude..
        /// </summary>
        internal static string Longitude_InvalidFormat {
            get {
                return ResourceManager.GetString("Longitude_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the right-most number can be a floating-point value..
        /// </summary>
        internal static string Longitude_OnlyRightmostIsDecimal {
            get {
                return ResourceManager.GetString("Longitude_OnlyRightmostIsDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Position.DistanceTo method requires a non-null ellipsoid parameter..
        /// </summary>
        internal static string Position_DistanceTo_Null_Ellipsoid {
            get {
                return ResourceManager.GetString("Position_DistanceTo_Null_Ellipsoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified format could not be fully recognized as a spherical or UTM coordinate..
        /// </summary>
        internal static string Position_InvalidFormat {
            get {
                return ResourceManager.GetString("Position_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified format could not be fully recognized as a speed measurement..
        /// </summary>
        internal static string Speed_InvalidFormat {
            get {
                return ResourceManager.GetString("Speed_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit portion of the speed measurement could not be recognized..
        /// </summary>
        internal static string Speed_InvalidUnitPortion {
            get {
                return ResourceManager.GetString("Speed_InvalidUnitPortion", resourceCulture);
            }
        }
    }
}
